sample:
    category:
        type: text
        primary: True
        default: !!null
    process:
        type: text
        primary: True
        default: !!null
    subprocess:
        type: text
        primary: True
        default: PROCESS
    name:
        type: text
        default: !!null
#    name_proper:
#        type: text
#        default: NAME
#    name_proper_latex:
#        type: text
#        default: !!null
#    name_proper_root:
#        type: text
#        default: !!null
    data:
        type: integer
        default: 0
    signal:
        type: integer
        default: 0
    path:
        type: text
        default: !!null
    luminosity:
        type: real
        default: 38180
    parameter1:
        type: real
        default: !!null
    parameter2:
        type: real
        default: !!null
    parameter3:
        type: real
        default: !!null
    parameter4:
        type: real
        default: !!null
    sigma:
        type: real
        default: !!null
    json:
        type: text
        default: !!null
    time:
        type: real
        default: 0

miniaod:
    category:
        type: text
        primary: True
        default: PARENT
    process:
        type: text
        primary: True
        default: PARENT
    subprocess:
        type: text
        primary: True
        default: PARENT
    generation:
        type: text
        primary: True
        default: !!null
    name:
        type: text
        default: !!null
    data:
        type: integer
        default: PARENT
    instance:
        type: text
        default: global
    das:
        type: integer
        default: 1
    path:
        type: text
        default: !!null
    cut:
        type: text
        default: "1"
    n:
        type: integer
        default: !!null
    preweight:
        type: real
        default: 1
    weight:
        type: real
        default: 1
    ttree:
        type: text
        default: Events
    json:
        type: text
        default: !!null
    lhe_path:
        type: text
        default: !!null
    lhe_cut:
        type: text
        default: !!null
    lhe_n:
        type: integer
        default: N
    mask:
        type: text
        default: !!null
    time:
        type: real
        default: 0

tuple:
    category:
        type: text
        primary: True
        default: PARENT
    process:
        type: text
        primary: True
        default: PARENT
    subprocess:
        type: text
        primary: True
        default: !!null
    generation:
        type: text
        primary: True
        default: spring15
    suffix:
        type: text
        primary: True
        default: "1"
    data:
        type: integer
        default: PARENT
    path:
        type: text
        default: !!null
    cut:
        type: text
        default: "1"
    n:
        type: integer
        default: !!null
    preweight:
        type: real
        default: 1
    weight:
        type: real
        default: PARENT
    json:
        type: text
        default: !!null
    time:
        type: real
        default: 0
